# Generated by Django 3.1.6 on 2021-02-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
