# Generated by Django 3.1.6 on 2021-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site_app', '0004_profile_image_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_avatar',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
