# Generated by Django 3.1.6 on 2021-02-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site_app', '0005_auto_20210221_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_image_post',
            field=models.ImageField(default='default_blog_image.jpg', upload_to=''),
        ),
    ]
