# Generated by Django 3.1.6 on 2021-02-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site_app', '0006_blogpost_blog_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
